### ISSUE TITLE
 ucs_vnic_template NoneType exception on vlans_list absent

### ISSUE THREAD

**Issue by lingfish** [CiscoUcs/ucsm-ansible#107]
Hi,

When setting `state: absent` on a VLAN in `vlans_list`, and that VLAN is already removed from a vNIC template, I get:
```
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ucs_vnic_template_payload_kPQCcA/__main__.py", line 354, in main
    ucs.login_handle.remove_mo(mo_1)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/ucsmsdk/ucshandle.py", line 696, in remove_mo
    mo.status = "deleted"
```

I think the expectation of idempotency is right here, instead of a crash ;)

The issue mainly is that the return from `ucs.login_handle.query_dn(child_dn)` isn't checked at all.

https://github.com/CiscoUcs/ucsm-ansible/blob/master/library/ucs_vnic_template.py#L353

The play error:
```
"msg": "setup error: 'NoneType' object has no attribute 'status' "
```

**Comment by lingfish** [comment]
Hi, no thoughts on this?

**Comment by dsoper2** [comment]
Sorry we missed this when initially file - we'll take a look and work a fix so that absent is an idempotent operation.  Thanks!
