### ISSUE TITLE
ucs_vnic_template.py - vlans in vlan_list are not getting removed when updating template

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoUcs/ucsm-ansible#46]
I created a vNIC template with a single access VLAN defined in the vlan_list.

Realized I had used a different VLAN name when creating the vlan so I corrected it in the vlan_list.

When I re-ran ansible-playbook, the old name was not removed from the list of VLANs on the vNIC.  Only the new VLAN name was added to the vNIC template.

Shouldn't it remove VLANs not defined in the ucs_vnic_template task and add the missing VLANs?

**Comment by SDBrett** [comment]
PR: https://github.com/CiscoUcs/ucsm-ansible/pull/77

**Comment by dsoper2** [comment]
SDBrett's PR #77 is now merged.  VLANs in vlan_list can be removed with state: absent
