### ISSUE TITLE
Add VLAN X, then associate that VLAN X with Service Profile Y

### ISSUE THREAD

**Issue by holmahenkel** [CiscoUcs/ucsm-ansible#96]
Hi,

Disclaimer - I'm a complete UCS n00b! 

Trying to perform the seemingly two simple steps using Ansible:

1. Add VLAN X
2. Associate that VLAN X with Service Profile Y

The VLAN part is handled by the `ucs_vlans` module, but then `ucs_service_profile_template` doesn't seem to have an option for VLANs specifically.

Is there some obvious intermediate step I'm missing here? Do I have to go via something like `ucs_lan_connectivity` first?

Any pointers would be highly appreciated!

Have a nice day.

Fredrik

**Comment by dsoper2** [comment]
ucs_service_profile_template doesn't support direct vNIC creation with VLANs.  You can create vnic templates (with ucs_vnic_template) which specify vNICs and then create lan connectivity policies (ucs_lan_connectivity).  Reach out with any other questions.

**Comment by holmahenkel** [comment]
Ah, OK I see. We need to introduce these additional steps first.

Thank you very much, @dsoper2 !
