### ISSUE TITLE
Prepare repo for installing ucsm-ansible via pip and git+https

### ISSUE THREAD

**Issue by hrupprecht** [CiscoUcs/ucsm-ansible#97]
Try to install ucsm-ansible via
```pip install git+https://github.com/CiscoUcs/ucsm-ansible.git```
fails

Please prepare repo
```
11:19 $ pip install git+https://github.com/CiscoUcs/ucsm-ansible.git
Collecting git+https://github.com/CiscoUcs/ucsm-ansible.git
  Cloning https://github.com/CiscoUcs/ucsm-ansible.git to /private/var/folders/7x/6ft2ttdn3b91hztrkvptgyt40000gn/T/pip-req-build-Pgyjby
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/private/var/folders/7x/6ft2ttdn3b91hztrkvptgyt40000gn/T/pip-req-build-Pgyjby/setup.py'```

**Comment by dsoper2** [comment]
There is currently not support for scripted install/uninstall to avoid collision with Ansible hosted modules and ongoing maintenance. You can specfiy this repo as a library and module_utils location with env variables or command line options (e.g., ANSIBLE_LIBRARY=./library ANSIBLE_MODULE_UTILS=./utils ansible-playbook ..). Alternatively, your .ansible.cfg file can be updated to use this repo as the library and module_utils path with the following:

[defaults]
library = <path to ucsm-ansible clone>/library
module_utils = <path to ucsm-ansible clone>/utils
See the install section of the README for step-by-step install and usage instructions.

**Comment by hrupprecht** [comment]
Hi David,
OK, going to include it as a git submodule and will adjust ansible config
